apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: publish
build:
  artifacts:
  - image: nats-publish
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kustomize
