apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: request
build:
  artifacts:
  - image: nats-request
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kustomize
