apiVersion: apps/v1
kind: Deployment
metadata:
  name: stan-publish
  labels:
    app: stan-publish
spec:
  selector:
    matchLabels:
      app: stan-publish
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stan-publish
    spec:
      containers:
      - name: stan-publish
        image: stan-publish:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: NATS_URL
          value: nats://nats-cluster.nats-io.svc.cluster.local:4222
      restartPolicy: Always
