apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: stan-publish
build:
  artifacts:
  - image: stan-publish
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kustomize
