apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-reply
  labels:
    app: nats-reply
spec:
  selector:
    matchLabels:
      app: nats-reply
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nats-reply
    spec:
      containers:
      - name: nats-reply
        image: nats-reply:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: NATS_URL
          value: nats://nats-cluster.nats-io.svc.cluster.local:4222
      restartPolicy: Always
